Fix error on completed_registration_spec test
raise_not_found_error: false option should be also be set in the test environment.
When running completed_registration_spec test, Registrant.find_by(email: subject.email) was rendering error instead of nil